{
 "title": "Code Execution Engine",
 "time": { "from": "now-42m", "to": "now-37m" },
 "panels": [
  {
   "title": "Worker Creation Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(traces_span_metrics_duration_milliseconds_sum{span_name=\"Create container\"}[5m])\n/\nrate(traces_span_metrics_duration_milliseconds_count{span_name=\"Create container\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(traces_span_metrics_duration_milliseconds_sum{span_name=\"ExecuteCode\"}[5m])\n/\nrate(traces_span_metrics_duration_milliseconds_count{span_name=\"ExecuteCode\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Web Server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(traces_span_metrics_duration_milliseconds_sum{span_name=\"WebServer\"}[5m])\n/\nrate(traces_span_metrics_duration_milliseconds_count{span_name=\"WebServer\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Minio Uploads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(traces_span_metrics_duration_milliseconds_sum{span_name=\"MinIO/Upload\"}[5m])\n/\nrate(traces_span_metrics_duration_milliseconds_count{span_name=\"MinIO/Upload\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Minio Downloads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(traces_span_metrics_duration_milliseconds_sum{span_name=\"MinIO/Download\"}[5m])\n/\nrate(traces_span_metrics_duration_milliseconds_count{span_name=\"MinIO/Download\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Queue P50",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.50,\n  rate(\n    job_queue_duration_seconds_bucket[6m]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}