{
 "title": "Wolf",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Worker Creation - P99",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le) (\n    rate(traces_span_metrics_duration_milliseconds_bucket{span_name=\"Create container\"}[2m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker Creation - P95",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le) (\n    rate(traces_span_metrics_duration_milliseconds_bucket{span_name=\"Create container\"}[2m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker Creation - P50",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le) (\n    rate(traces_span_metrics_duration_milliseconds_bucket{span_name=\"Create container\"}[2m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue Wait Time - P99",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le) (\n    rate(job_queue_duration_seconds_bucket[2m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue Wait Time- P95",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le) (\n    rate(job_queue_duration_seconds_bucket[2m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue Wait Time- P50",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le) (\n    rate(job_queue_duration_seconds_bucket[2m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker Execute - P99",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le) (\n    rate(traces_span_metrics_duration_milliseconds_bucket{span_name=\"ExecuteCode\"}[2m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker Execute - P95",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le) (\n    rate(traces_span_metrics_duration_milliseconds_bucket{span_name=\"ExecuteCode\"}[2m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker Execute - P50",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le) (\n    rate(traces_span_metrics_duration_milliseconds_bucket{span_name=\"ExecuteCode\"}[2m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Minio Uploads - P99",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le) (\n    rate(traces_span_metrics_duration_milliseconds_bucket{span_name=\"MinIO/Upload\"}[2m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Minio Uploads - P95",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le) (\n    rate(traces_span_metrics_duration_milliseconds_bucket{span_name=\"MinIO/Upload\"}[2m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Minio Uploads - P50",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le) (\n    rate(traces_span_metrics_duration_milliseconds_bucket{span_name=\"MinIO/Upload\"}[2m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wolf Server - P99",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le) (\n    rate(traces_span_metrics_duration_milliseconds_bucket{span_name=\"wolf_server\"}[2m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wolf Server - P95",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le) (\n    rate(traces_span_metrics_duration_milliseconds_bucket{span_name=\"wolf_server\"}[2m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wolf Server - P50",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le) (\n    rate(traces_span_metrics_duration_milliseconds_bucket{span_name=\"wolf_server\"}[2m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}